"""
Build script for qdb-embedded CPython C extension.

Sources are compiled directly from the parent repository's src/ directory;
no vendoring or pkg-config invocation is needed.

qdb_version.h is generated by CMake but is not committed to the source tree.
This script generates a minimal copy into python/_gen_include/ so that no
prior cmake run is required to build the Python package.
"""

import os
import re
import sys
import pathlib
from setuptools import setup, Extension, find_packages

HERE = pathlib.Path(__file__).parent.resolve()
ROOT = HERE.parent

# ---------------------------------------------------------------------------
# Parse version from the canonical source: ../CMakeLists.txt
# ---------------------------------------------------------------------------

cmake_text = (ROOT / "CMakeLists.txt").read_text()
m = re.search(r'project\s*\(\s*qdb\s+VERSION\s+([\d.]+)', cmake_text)
if not m:
    raise RuntimeError("Cannot parse QDB version from CMakeLists.txt")
_ver = m.group(1)
_major, _minor, _patch = _ver.split(".")

# ---------------------------------------------------------------------------
# Ensure qdb_version.h is available.
# Prefer an existing cmake-generated copy; fall back to generating one.
# ---------------------------------------------------------------------------

_gen_dir = HERE / "_gen_include"
_gen_dir.mkdir(exist_ok=True)
_ver_h = _gen_dir / "qdb_version.h"
_ver_h.write_text(
    "#ifndef QDB_VERSION_H\n"
    "#define QDB_VERSION_H\n"
    f'#define QDB_VERSION_STRING "{_ver}"\n'
    f"#define QDB_VERSION_MAJOR  {_major}\n"
    f"#define QDB_VERSION_MINOR  {_minor}\n"
    f"#define QDB_VERSION_PATCH  {_patch}\n"
    f"#define QDB_VERSION_NUMBER "
    f"({_major}*10000 + {_minor}*100 + {_patch})\n"
    "#endif /* QDB_VERSION_H */\n"
)

# ---------------------------------------------------------------------------
# Extension definition
# ---------------------------------------------------------------------------

if sys.platform == "win32":
    _extra_compile = ["/std:c17"]
    _libraries = ["ws2_32"]
else:
    _extra_compile = ["-std=c17"]
    _libraries = []

# setuptools requires paths relative to setup.py, not absolute paths.
ext = Extension(
    "qdb._qdb",
    sources=[
        "qdb/_qdb.c",
        "../src/qdb.c",
        "../src/qdb_crc32.c",
        "../src/qdb_io.c",
        "../src/qdb_platform.c",
        "../src/qdb_replay.c",
        "../src/qdb_state.c",
    ],
    include_dirs=["../include", "_gen_include"],
    extra_compile_args=_extra_compile,
    libraries=_libraries,
)

setup(
    packages=["qdb"],
    ext_modules=[ext],
)
